//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splitwords
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public string word1 { get; set; }
        public string frequency { get; set; }
        public int id { get; set; }
        public Nullable<int> id_people { get; set; }
    }
}
